spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ds?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4_general_ci
spring.datasource.username=root
spring.datasource.password=Zhn123456789,

# MyBatis-Plus XML 配置文件路径
mybatis-plus.mapper-locations=classpath:mapper/*.xml
#自动驼峰命名
mybatis-plus.configuration.map-underscore-to-camel-case=true 

#主键策略
mybatis-plus.global-config.db-config.id-type=auto
